Repository smash-transport/sparkx, pull requests merged in 2023-11, with the labels that each got.

#131 Strangeness handling for density smearing
  docs/source/classes/EventCharacteristics/index.rst
  src/sparkx/Lattice3D.py
  src/sparkx/Oscar.py
  src/sparkx/Particle.py
Labels: enhancement

#135 Add option to import SPARKX with *
  src/sparkx/__init__.py
  src/sparkx/flow/__init__.py
Labels: enhancement

#130 Roch/additional particle info
  docs/source/classes/Particle/index.rst
  src/sparkx/Particle.py
Labels: enhancement

#137 Density smearing in Milne and Minkowski coordinates
  docs/source/classes/EventCharacteristics/index.rst
  docs/source/classes/Lattice3D/index.rst
  src/sparkx/EventCharacteristics.py
  src/sparkx/Lattice3D.py
  src/sparkx/Oscar.py
  src/sparkx/Particle.py
Labels: enhancement

#144 Add CHANGELOG file
  CHANGELOG.md
Labels: documentation, enhancement

#149 Fix single event read-in in Oscar and Jetscape
  CHANGELOG.md
  src/sparkx/Jetscape.py
  src/sparkx/Oscar.py
Labels: bug
