Repository smash-transport/sparkx, pull requests merged in 2024-11, with the labels that each got.

#297 Add new filters + fix statical typing for external packages
  CHANGELOG.md
  docs/source/classes/BaseStorer/index.rst
  docs/source/classes/Particle/index.rst
  src/sparkx/BaseStorer.py
  src/sparkx/CentralityClasses.py
  src/sparkx/EventCharacteristics.py
  src/sparkx/Filter.py
  src/sparkx/Histogram.py
  src/sparkx/Jackknife.py
  src/sparkx/JetAnalysis.py
  src/sparkx/Jetscape.py
  src/sparkx/Lattice3D.py
  src/sparkx/MultiParticlePtCorrelations.py
  src/sparkx/Oscar.py
  src/sparkx/Particle.py
  src/sparkx/Utilities.py
  src/sparkx/flow/EventPlaneFlow.py
  src/sparkx/flow/FlowInterface.py
  src/sparkx/flow/GenerateFlow.py
  src/sparkx/flow/LeeYangZeroFlow.py
  src/sparkx/flow/PCAFlow.py
  src/sparkx/flow/QCumulantFlow.py
  src/sparkx/flow/ReactionPlaneFlow.py
  src/sparkx/flow/ScalarProductFlow.py
  src/sparkx/loader/JetscapeLoader.py
  src/sparkx/loader/OscarLoader.py
  src/sparkx/loader/ParticleObjectLoader.py
  tests/test_Filter.py
  tests/test_Jetscape.py
  tests/test_Oscar.py
  tests/test_Particle.py
Labels: bug, documentation, enhancement

#299 Roch/fix filters oscar jetscape
  docs/source/classes/BaseStorer/index.rst
  src/sparkx/BaseStorer.py
  src/sparkx/Filter.py
  src/sparkx/Jetscape.py
  src/sparkx/Oscar.py
  src/sparkx/loader/JetscapeLoader.py
Labels: bug, documentation

#300 Update contributors and python version
  CHANGELOG.md
  CONTRIBUTORS.md
  pyproject.toml
Labels: documentation

#302 Improve quickstart
  docs/source/quickstart.rst
  src/sparkx/Histogram.py
Labels: bug, documentation

#309 unit test for values out of range in Histogram
  tests/test_Histogram.py
Labels: tests

#313 Change small things in the documentation
  README.md
  docs/source/index.rst
  docs/source/quickstart.rst
  src/sparkx/BaseStorer.py
  src/sparkx/CentralityClasses.py
  src/sparkx/EventCharacteristics.py
  src/sparkx/Histogram.py
  src/sparkx/Jackknife.py
  src/sparkx/Jetscape.py
  src/sparkx/MultiParticlePtCorrelations.py
  src/sparkx/Oscar.py
  src/sparkx/Particle.py
  src/sparkx/ParticleObjectStorer.py
  src/sparkx/flow/EventPlaneFlow.py
  src/sparkx/flow/LeeYangZeroFlow.py
  src/sparkx/flow/PCAFlow.py
  src/sparkx/flow/QCumulantFlow.py
  src/sparkx/flow/ScalarProductFlow.py
  src/sparkx/loader/BaseLoader.py
  src/sparkx/loader/JetscapeLoader.py
  src/sparkx/loader/OscarLoader.py
  src/sparkx/loader/ParticleObjectLoader.py
Labels: documentation

#316 Checkout merge commit and not the branch
  .github/workflows/code_formatting.yml
Labels: bug

#322 Run formatter workflow on push to devel or main
  .github/workflows/code_formatting.yml
Labels: bug

#324 New formatter workflow test
  .github/workflows/code_formatting.yml
Labels: bug

#340 Fix centrality class example, enhance documentation
  src/sparkx/BaseStorer.py
  src/sparkx/CentralityClasses.py
  src/sparkx/EventCharacteristics.py
  src/sparkx/Filter.py
  src/sparkx/Histogram.py
  src/sparkx/Jackknife.py
  src/sparkx/Jetscape.py
  src/sparkx/MultiParticlePtCorrelations.py
  src/sparkx/Oscar.py
  src/sparkx/Particle.py
  src/sparkx/ParticleObjectStorer.py
  src/sparkx/loader/BaseLoader.py
  src/sparkx/loader/JetscapeLoader.py
  src/sparkx/loader/OscarLoader.py
  src/sparkx/loader/ParticleObjectLoader.py
  tests/test_BaseStorer.py
  tests/test_EventCharacteristics.py
  tests/test_Filter.py
  tests/test_Jetscape.py
  tests/test_Oscar.py
  tests/test_Particle.py
Labels: documentation
